services:
    validator.constraint.maxentityhomepage:
        class: ZIMZIM\Bundles\CategoryProductBundle\Validator\Constraints\ConstraintMaxEntityHomePageValidator
        arguments: [ @doctrine.orm.entity_manager, %zimzim_bundles_category_product.max_element% ]
        tags:
            - { name: validator.constraint_validator, alias: maxentityhomepage }