zimzim_categoryproduct_product:
    path:     /
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:index" }

zimzim_categoryproduct_product_show:
    path:     /{id}/show
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:show" }

zimzim_categoryproduct_product_new:
    path:     /new
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:new" }

zimzim_categoryproduct_product_create:
    path:     /create
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:create" }
    requirements: { _method: post }

zimzim_categoryproduct_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:edit" }

zimzim_categoryproduct_product_update:
    path:     /{id}/update
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:update" }
    requirements: { _method: post|put }

zimzim_categoryproduct_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Product:delete" }
    requirements: { _method: post|delete }
