zimzim_categoryproduct_category_listslug:
    path:     /{slug}/
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Category:listcategorybyslug" }
    requirements:
        _method:  GET
        slug: \w+

zimzim_categoryproduct_category_listslugnull:
    path:     /
    defaults: { _controller: "ZIMZIMBundlesCategoryProductBundle:Category:listcategorybyslug"}
    requirements:
        _method:  GET