services:
    zimzim_cpbundle.form.type.zimzimcollectionformtype:
        class: ZIMZIM\CPBundle\Form\Type\ProductType
        tags:
            - { name: form.type, alias: zimzim_cpbundle_producttype }